// <auto-generated />
namespace ServerUsersOwinAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deletedStatusfromAuthTokens : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletedStatusfromAuthTokens));
        
        string IMigrationMetadata.Id
        {
            get { return "201602031523179_deletedStatusfromAuthTokens"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
