// <auto-generated />
namespace GetWebSitesToJPG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedURLParam_ImageCropData_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedURLParam_ImageCropData_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201511302000415_addedURLParam_ImageCropData_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
